server:
  port: 8082
spring:
  application:
    name: 'transaction'
  data:
    mongodb:
      authentication-database: 'admin'
      username: developer
      password: mongodb
      database: 'point_transaction'
      port: 27017
      host: 'localhost'